config:
    info: "master branch,springcould-config/config-dev.yml version=6"
eureka:
  client:
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka,http://eureka8002.com:8002/eureka,http://eureka8001.com:8003/eureka
